### PR TITLE
Update the "about" section of the recipe

### PR DESCRIPTION
**Pull request by mdpiper**
The PR touches up the "about" section of the recipe, which contained some stale information.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mdpiper** [comment]
@conda-forge-admin, please rerender

**Comment by mdpiper** [comment]
@mcflugen I'm not a recipe maintainer (unless you'd like to make me one), so I can't merge this PR.

**Comment by mcflugen** [comment]
@mdpiper I added you as a maintainer.

**Comment by mdpiper** [comment]
> @mdpiper I added you as a maintainer.

Thanks! Although it appears I can't merge this PR (maybe because I'm gaining write access through it).

**Comment by mcflugen** [comment]
@mdpiper That's what I figured.

**Pull request merged**
